# Generated by Django 2.2.5 on 2019-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=120, verbose_name='URL')),
                ('text', models.TextField(verbose_name='Текст')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='imeges/', verbose_name='Баннер')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('descripton', models.CharField(max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
