# Generated by Django 2.2.5 on 2019-09-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('header', models.CharField(blank=True, max_length=240, null=True, verbose_name='Подзаголовок')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка техники')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Баннер')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('descripton', models.CharField(max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Category', verbose_name='Выбор категории')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
