# Generated by Django 2.2.5 on 2019-09-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='sort',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='model',
            name='sub_header',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='model',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Category', verbose_name='Выбор категории'),
        ),
        migrations.AlterField(
            model_name='model',
            name='header',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Заголовок'),
        ),
    ]
